### PR TITLE
name change for PearAI server model panel

### PR DESCRIPTION
**Pull request by Alexx1105**
- Changed "Add PearAI Server" button to "Start Coding 😎" for the server model panel. 

- Still working on the other asked for changes but wanted to send the PR for this first change.

---
Before:
image

After:
CleanShot 2024-07-05 at 12 43 09@2x

Maintainer edited: related to: https://github.com/trypear/pearai-app/issues/157

### CODE REVIEW

**Comment by MaySoMusician** [comment]
Could you attach some screenshot *before* and *after* the change? @Alexx1105

**Comment by Alexx1105** [comment]
@MaySoMusician do you mean of the change itself? 
CleanShot 2024-07-05 at 11 20 51@2x

**Comment by MaySoMusician** [comment]
e.g. see https://github.com/trypear/pearai-submodule/pull/54

**Comment by Alexx1105** [comment]
> Could you attach some screenshot *before* and *after* the change? @Alexx1105 

@MaySoMusician before and after shots added

**Review by nang-dev — APPROVED** [review]

**Comment by nang-dev** [comment]
ok

**Comment by nang-dev** [comment]
we need to make a lot of changes to this ui still

**Pull request merged**
