### PR TITLE
open tutorial button on help page will now open "/" if user is logged in

### PR DESCRIPTION
**Pull request by Alvarixxs**
## Description ✏️

Closes https://github.com/trypear/pearai-app/issues/281

What changed? Feel free to be brief.

- open tutorial button will now navigate to "/" rather than "onboarding" if user is already logged in
- tutorial is still opened

## Checklist ✅

[✅] I have added screenshots (if UI changes are present).
[✅] I have done a self-review of my code.
[✅] I have manually tested my code (if applicable).

### CODE REVIEW

**Comment by nang-dev** [comment]
@Alvarixxs  hmm i tested this and it didnt work for me :(

**Comment by nang-dev** [comment]
Did it work for you?

**Comment by Alvarixxs** [comment]
hi, what doesn't work?
Is the problem onboarding not showing when "/onboarding" has already been visited? We save a variable in local storage which makes sure "/onboarding" cannot be visited again once it has been completed. I can change that.

**Comment by nang-dev** [comment]
sorry i shouldve been more specific.

by not working i mean that

login -> open tutorial -> it goes to the onboarding page

**Comment by Alvarixxs** [comment]
I believe that works for me, I'll send a vid.

**Comment by Alvarixxs** [comment]
[Screencast from 27-08-24 20:40:16.webm](https://github.com/user-attachments/assets/de74a6d8-6fde-4061-8dcd-c7c263a64006)

**Comment by Alvarixxs** [comment]
gimme a sec

**Comment by Alvarixxs** [comment]
yea this does not work, having difficulties extracting user authentication from within the gui of the app

**Comment by nang-dev** [comment]
nw good try

**Comment by nang-dev** [comment]
ill put this as help wanted

**Pull request closed without merging**
