### PR TITLE
[FEAT] Disables Use codebase until Indexing Completes - Waits for User Input

### PR DESCRIPTION
**Pull request by charlwillia6**
## Description ✏️

This feature disables the "Use codebase" button and CTRL/CMD+ENTER commands if indexing has not completed.  It also requires user input in the chat box.

image
image
image
image

## Checklist ✅

- [x] I have added screenshots (if UI changes are present).
- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).

### CODE REVIEW

**Comment by Fryingpannn** [comment]
Yo great work charl. I tested on my end and it works great. I think there are just 2 things needed before this can get merged. We need some visibility for the user regarding indexing:


1. When the sidebar is small, the indicating for cmd + enter for codebase context disappears. I noticed during user testing on laptops many users because of this don't know they can use codebase context.
    - **Solution**: instead of completely disappearing the use codebase context button and enter button, make them wrap into a new row. That way even when the sidebar is small, user can still see it
Screenshot 2024-10-28 at 2 35 48 PM

2. Since the button is disabled at times, the user needs to have some understanding of why. **We should add a tooltip** on hover (over the codebase button), where it says either 
   - If paused; Unpause codebase index to use codebase context.
   - If loading: Indexing still in progress, please wait.
   - If ready: Use codebase contex

**Comment by charlwillia6** [comment]
@Fryingpannn Great feedback. After I am done with this other high priority project for PearAI, I will implement these requests and push them to this PR. I'll leave a comment when I have completed this.

**Comment by charlwillia6** [comment]
> Yo great work charl. I tested on my end and it works great. I think there are just 2 things needed before this can get merged. We need some visibility for the user regarding indexing:
> 
> 1. When the sidebar is small, the indicating for cmd + enter for codebase context disappears. I noticed during user testing on laptops many users because of this don't know they can use codebase context.
>    
>    * **Solution**: instead of completely disappearing the use codebase context button and enter button, make them wrap into a new row. That way even when the sidebar is small, user can still see it
> 
> Screenshot 2024-10-28 at 2 35 48 PM
> 2. Since the button is disabled at times, the user needs to have some understanding of why. **We should add a tooltip** on hover (over the codebase button), where it says either
>    
>    * If paused; Unpause codebase index to use codebase context.
>    * If loading: Indexing still in progress, please wait.
>    * If ready: Use codebase contex

I added these features and merged main into this branch:

image
image
image

**Comment by charlwillia6** [comment]
Closing this PR due to the chat interface getting redesigned.  I will open a new PR if this functionality needs to be added.

**Pull request closed without merging**
