### PR TITLE
Add Hacker style theme as option

### PR DESCRIPTION
**Pull request by andrewjhopkins**
Adds Palm Synthwave as a default theme built into the PearAI extension

Closes [#289](https://github.com/trypear/pearai-app/issues/289)

image

## Checklist ✅

- [x] I have added screenshots (if UI changes are present).
- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).

### CODE REVIEW

**Comment by nang-dev** [comment]
This is perfect!!! Can we call it "Hacker"? :)

**Comment by andrewjhopkins** [comment]
> This is perfect!!! Can we call it "Hacker"? :)

done

Screenshot 2024-09-04 at 5 50 05 PM

**Comment by ICEPrey** [comment]
i thought we were going with @tanishq-xin theme?

**Comment by nang-dev** [comment]
@Fryingpannn @ICEPrey @andrewjhopkins yes, hacker shouldnt be our default . Sorry for the confusion there andrew. This adds "Hacker" as an option right? If yes, will merge! :D

**Review by nang-dev — APPROVED** [review]

**Comment by andrewjhopkins** [comment]
> @Fryingpannn @ICEPrey @andrewjhopkins @tanishq-xin yes, hacker shouldnt be our default . Sorry for the confusion there andrew. This adds "Hacker" as an option right? If yes, will merge! :D

Yes, it's not default as in what the users will see on first install. Just it's a built in theme that users can select without installing an additional extension. So option is probably the better word.

**Comment by ICEPrey** [comment]
> > @Fryingpannn @ICEPrey @andrewjhopkins @tanishq-xin yes, hacker shouldnt be our default . Sorry for the confusion there andrew. This adds "Hacker" as an option right? If yes, will merge! :D
> 
> Yes, it's not default as in what the users will see on first install. Just it's a built in theme that users can select without installing an additional extension. So option is probably the better word.

Oh my bad didn't catch that, sorry about that

**Comment by nang-dev** [comment]
@andrewjhopkins wouldnt this be better added in the pearai-app directory? 🤔

**Comment by andrewjhopkins** [comment]
> @andrewjhopkins wouldnt this be better added in the pearai-app directory? 🤔

We can do that too. That would be better because it would allow the theme to run even if the user is in restricted mode which blocks the pear extension. I was a bit hesitant to modify the forked vscode code because I am not sure if you guys continue to pull in updates, but if you are good with it we can do that. 

I created another PR for putting it directly in the pearai-app directory https://github.com/trypear/pearai-app/pull/300
You can merge whichever is preferred and close out the other.

**Pull request closed without merging**
