### PR TITLE
Open extension panel during first onboarding

### PR DESCRIPTION
**Pull request by MaySoMusician**
### What

- fixes: https://github.com/trypear/pearai-app/issues/131

Once the extension is activated, we'll open the pane up so users can jump right into the onboarding and the tutorial.

If we can skip the model selection process (or wait until after the tutorial is done), we can immediately open the tutorial file as well.

### Video

https://github.com/trypear/pearai-submodule/assets/34566290/47863d4d-39fe-4393-b06a-dd640bffcc5c

### CODE REVIEW

**Comment by nang-dev** [comment]
this is renamed now

**Comment by nang-dev** [comment]
banger. we renamed it to pearai instead of continue though now i can do that tyty

**Comment by MaySoMusician** [comment]
> banger. we renamed it to pearai instead of continue though now i can do that tyty

@nang-dev Addressed on https://github.com/trypear/pearai-submodule/pull/55/commits/141e694fdcc2d49521e1201bc42c3e08e877f491 !

**Review by nang-dev — APPROVED** [review]

**Comment by nang-dev** [comment]
thanks so much!

**Pull request merged**
