### PR TITLE
Refresh search results upon reindexing context providers

### PR DESCRIPTION
**Pull request by jespiron**
## Description

**Context:** [Issue](https://github.com/trypear/pearai-app/issues/196)

**Before**
1. Rename B.py to BBBBB.py
2. Open chat, type "@", search for BBBBB.py
3. **[Issue]** BBBBB.py not found, B.py is found with unusable content
4. Force re-indexing by clicking green button, see same issue

**BBBBB.py not found:** [video](https://github.com/user-attachments/assets/32fafcd6-2a0f-4334-81dc-07107df7c5d3), 
>"Hi! It seems like we’ve had a series of Python files with similar contents. If you’d like to chat about something else, I’m here to help!" - Llama, Midwestern nice

**Found file is unusable:** [screenshot](https://github.com/user-attachments/assets/c9fc6e6f-6621-4ab6-8aac-411e730ff984)

**After**
1. Rename B.py to BBBBB.py
2. Open chat, type "@", search for BBBBB.py
3. BBBBB.py is found, B.py is removed as desired (if not found, wait a few seconds)
4. If don't want to wait, force re-indexing by clicking green button and see desired results

BBBBB.py is found: [video](https://github.com/user-attachments/assets/cb048555-df66-4603-a008-53eb683e0c93)
Found file matches desired contents: [screenshot](https://github.com/user-attachments/assets/b0e2b8c0-32e4-48a7-b316-1cdd4443cf1c)

>"A Python file with some actual code!"

## Change
**Fix**
The part that updates search results is this [useEffect](https://github.com/trypear/pearai-submodule/blob/971ad37637d257b6f7033805d4843f3df142619a/gui/src/hooks/useSubmenuContextProviders.tsx#L102-L134).

In short, we want `useEffect(awesomeFunc, [dep1, dep2, ...])` to run awesomeFunc after we reindex CodeSnippetsCodebaseIndex, but it only runs when one of its dependencies dep1, dep2, ... change.

**This PR**
The added line sets one of the useEffect dependencies, `loaded`, to false, causing awesomeFunc to run.

### [optional reading] what this useEffect does
Logic in useEffect is correct, quick summary in case someone wants to investigate:
Each main menu item (the options *Files, Code, Docs...* that pop up on "@"), has submenu items (filenames like *A.py, B.py, ...*).
This useEffect indexes submenu items for each main menu item.
1. Creates one search engine (MiniSearch) per main menu item
7. Makes a loadSubmenuItems request for each main menu item
8. Indexes results into search engine of main menu item

From 2 to 3, full flow is send request loadSubmenuItems -> CodeContextProvider -> CodeSnippetsCodebaseIndex. Can read about indexing [here](https://github.com/trypear/pearai-submodule/tree/971ad37637d257b6f7033805d4843f3df142619a/core/indexing). Thanks @Himanshu-Singh-Chauhan for looking over indexing with me and verifying that problem was in UI, and thanks @Fryingpannn for onboarding and giving helpful points of contact

## Checklist

- [ ] The base branch of this PR is `preview`, rather than `main`

### CODE REVIEW

**Comment by Himanshu-Singh-Chauhan** [comment]
did you verify it, because it isn't working for me...
how long after renaming till it triggers refresh?

**Comment by jespiron** [comment]
hm, can you confirm that force reindexing works?
the work without forcing needs more investigation, but i'm fairly confident force reindexing works

i took some more videos to confirm:
**before change:** [video 2 - doesn't work, even with force reindex](https://github.com/user-attachments/assets/2ade80e5-6cbb-4caa-afba-c35676eb1167)
**after change:** [video 2 - works with force reindex](https://github.com/user-attachments/assets/4b603014-42b9-4ebb-b4f0-27cd361c78df)

**Comment by Fryingpannn** [comment]
Closing this since change has been made in https://github.com/trypear/pearai-submodule/pull/111

Tyvm for detailed PR description, helped me understand the code surrounding this issue a lot better!

**Comment by Fryingpannn** [comment]
Closing this since change has been made in https://github.com/trypear/pearai-submodule/pull/111

Tyvm for detailed PR description, helped me understand the code surrounding this issue a lot better!

**Pull request closed without merging**
