### PR TITLE
Filtering out system messages from Bedrock

### PR DESCRIPTION
**Pull request by ashvinnihalani**
## Description ✏️

Closes https://github.com/trypear/pearai-app/issues/336 

What changed? Feel free to be brief.

- Adding a map to exclude system messages
- Screenshots are helpful (if applicable).

## Checklist ✅

- [x] I have added screenshots (if UI changes are present).
- [x] I have done a self-review of my code.
- [X] I have manually tested my code (if applicable).

### CODE REVIEW

**Review by ICEPrey — APPROVED** [review]
https://github.com/continuedev/continue/pull/1951

**Comment by ashvinnihalani** [comment]
@ICEPrey Can you merge this I don't have merge permissions?

**Comment by ICEPrey** [comment]
> @ICEPrey Can you merge this I don't have merge permissions?

No I am not authorized to merge this pr just ask @Fryingpannn or @nang-dev

**Comment by nang-dev** [comment]
sure thanks

**Comment by nang-dev** [comment]
goat

**Pull request merged**
