### PR TITLE
Added slash command for v0

### PR DESCRIPTION
**Pull request by djarran**
## Description ✏️

Closes https://github.com/trypear/pearai-app/issues/314

Adds a new default slash command for allowing users to prompt AI to redirect to v0.

Basic functionality is there but prompt could do with some improvements.

To test, add the following to your config.json for the PearAI submodule (see bottom right of PearAI sidebar):

```
,
  "slashCommands": [
    ...
    {
      "name": "component",
      "description": "Generate a component using v0"
    }
  ]
```

## Checklist ✅

- [ ] I have added screenshots (if UI changes are present).
- [ ] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).

### CODE REVIEW

**Review by Fryingpannn — COMMENTED** [review]
Nice, tried it! Also added a commit!

Screenshot 2024-09-11 at 11 14 46 PM

image

**Comment by nang-dev** [comment]
Fixed merged conflicts that i caused for ya. is this good to push?

**Comment by nang-dev** [comment]
okay i think this looks good. merging

**Comment by nang-dev** [comment]
@Fryingpannn howd did u see this? 

i cant 
Screenshot 2024-09-17 at 5 05 35 PM

**Comment by nang-dev** [comment]
Screenshot 2024-09-17 at 5 12 16 PM

**Comment by nang-dev** [comment]
maybe im missin somethin here

**Comment by djarran** [comment]
Hey @nang-dev, are you still experiencing this issue? I can relook if this needs fixing

**Pull request merged**
