### PR TITLE
[PAUSED] feat: beginner context provider

### PR DESCRIPTION
**Pull request by ICEPrey**
## Description :pencil2:

Closes https://github.com/trypear/pearai-app/issues/321 (this should be a issue in pear-app)

What changed? Feel free to be brief.
- Created a new custom context provider called "BeginnerContextProvider".
- Implemented getContextItems method to return beginner-friendly instructions.
- Users can simply type "@Beginner" to activate this mode for their questions.

image
image
image

## Checklist :white_check_mark:

- [x] I have added screenshots (if UI changes are present).
- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).

### CODE REVIEW

**Review by Himanshu-Singh-Chauhan — APPROVED** [review]
nice.

**Comment by nang-dev** [comment]
Dang this is good. but lets pause this rq sorry ice. i think we want this to not be a command but in a Rules / Profiles section. Because i think a user will be a beginner for every prompt

**Comment by ICEPrey** [comment]
> Dang this is good. but lets pause this rq sorry ice. i think we want this to not be a command but in a Rules / Profiles section. Because i think a user will be a beginner for every prompt

i see makes sense let me know what the flow is/confirm it and then just tag me on discord or here and ill finish

**Comment by nang-dev** [comment]
Yo ice pan wanted this for demos so he merged one. my b .  Can u make a PR that merges this to a branch called 'begginner' so you'll be in the PR history <3

**Comment by ICEPrey** [comment]
lol you don't need to do all that can just delete if needed, thanks though

**Pull request merged**
