### PR TITLE
Revert "Added custom provider for PearAI backend (#58)" (#60)

### PR DESCRIPTION
**Pull request by Failure-Tech**
This reverts commit 204f043ae8fb74b51fe6b09d3646224bacc2e1d6.

## Description

new llm provider for claude 3.5 sonnet

## Checklist

- [ ] The base branch of this PR is `preview`, rather than `main`

### CODE REVIEW

**Comment by nang-dev** [comment]
?

**Comment by nang-dev** [comment]
feel free to explain, im a bit confused! this adds claude?

**Comment by Failure-Tech** [comment]
basically just adding an llm provider for claude 3.5 sonnet, good to keep
js in case, think we can setup after initial launch along w/ free trial as
well

**Comment by nang-dev** [comment]
we merged this! tysm!!

**Pull request closed without merging**
