### PR TITLE
[FEAT] Added auto scrolling and scroll to bottom button

### PR DESCRIPTION
**Pull request by charlwillia6**
## Description ✏️

Added auto scrolling for when you click Enter or press Enter on the keyboard for chats, Aider, and Perplexity.
Added a button that shows up if you scroll up that will take you back to the bottom
Removed unnecessary components
Fixed some styles

Note: To deactivate auto scrolling, the user only has to manually scroll up on the content.  This auto scrolling behavior also fixes the chat input box to the bottom of the screen when scrolling is enabled.  

auto-scroll
scroll-to-bottom-button

## Checklist ✅

- [x] I have added screenshots (if UI changes are present).
- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).

### CODE REVIEW

**Comment by Fryingpannn** [comment]
Looking at your PR right now, it seems like u have a lot of linting changes also included. It's hard to see the actual changes )::
is it possible to separate the linting changes into a different commit than the actual functionality changes.

I ran your branch on my local though, and it works! Nicee. Just two things to fix:
1. The "New Session" button should also be stickied with the chat input box. Right now if you scroll down, you can always see the chat box, but the new session button right below it is hidden until you fully scroll to the bottom, which makes the UI look a bit weird, cause at the very bottom it pushes the chat input box upwards a bit.
2. I like the go to bottom button you added. But it also appears at the very beginning when nothing is in the chat! Should only appear if scrolling is needed. E.g. try running Reload Webviews in command palette, the button appears in the chat regardless of any text being there.
Screenshot 2024-10-25 at 5 07 08 PM
Screenshot 2024-10-25 at 5 08 40 PM

**Comment by charlwillia6** [comment]
@Fryingpannn - I may need to close this PR and open another one maybe.  I am not sure.  I had format on save on, so it formatted each file I saved.  Also, some are code clean-up efforts. 

As for the download button showing up without scrolling, I can't replicate that on my end.  But I will look into it why that is and fix it.

**Comment by charlwillia6** [comment]
@Fryingpannn Oh, and the new session button being hidden while you scroll up was my design.  I will change that too.

**Comment by Fryingpannn** [comment]
Rip all the conflicts caused by linting XDDDDDDDDDDD 

I think best is if you copy paste your changes for the scrolling into new PR! Sorry for the troubles.. 😭

**Comment by charlwillia6** [comment]
> Rip all the conflicts caused by linting XDDDDDDDDDDD
> 
> I think best is if you copy paste your changes for the scrolling into new PR! Sorry for the troubles.. 😭

Okay.  It maybe a few days.  I will get a new PR up as soon as I can.

**Comment by charlwillia6** [comment]
Closing for now.  I will re-open when every thing is fixed.

**Pull request closed without merging**
